### ISSUE TITLE
Support for cacert without cert/key, support for username/password, http headers

### ISSUE THREAD

**Issue by lukas-vlcek** [ViaQ/watches-cli#6]
When secured communication is required we currently support passing all 3 certificates via pattern:

    [(--cacert=CACERT --cert=CERT --key=KEY)]

Meaning, client need to provide all 3 certs or nothing (nothing means no security is used).

We should support other use cases, like providing `cacert` and `username` and `password`. This would be pattern:

     [(--cacert=CACERT --username=USERNAME --password=PSWD)]

Where:

    --username    user_id
    --password    user password in plain text

**Comment by lukas-vlcek** [comment]
@richm which other option combinations we should support on top of currently supported

    --cacert=CACERT --cert=CERT --key=KEY

and above proposed

    --cacert=CACERT --username=USERNAME --password=PSWD

?

**Comment by richm** [comment]
Fixed by https://github.com/ViaQ/watches-cli/pull/13

We should support `--cacert` by itself in case someone wants to hit `https://host` with no authentication.

We should support `--header` by itself - it can be used for other than security/authentication.

The http implementation uses http_auth, which requires both `--username` and `--password` if either are specified.

**Comment by lukas-vlcek** [comment]
@richm Can we close this ticket now or is something still missing?

**Comment by richm** [comment]
closed via https://github.com/richm/watches-cli/commit/eeb7784c8771d7d27871d7bda1816cfcc41864b6
